name: Deploy to AWS Elastic Beanstalk

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_APP_KEY: ${{ secrets.ENVKEY_APP_KEY }}  
          envkey_AWS_ACCESS_KEY_ID: ${{ secrets.ENVKEY_AWS_ACCESS_KEY_ID }}  
          envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.ENVKEY_AWS_SECRET_ACCESS_KEY }}  
          envkey_BCRYPT_ROUNDS: ${{ secrets.ENVKEY_BCRYPT_ROUNDS }}  
          envkey_DB_CONNECTION: ${{ secrets.ENVKEY_DB_CONNECTION }}  
          envkey_DB_DATABASE: ${{ secrets.ENVKEY_DB_DATABASE }}  
          envkey_DB_HOST: ${{ secrets.ENVKEY_DB_HOST }}  
          envkey_DB_PASSWORD: ${{ secrets.ENVKEY_DB_PASSWORD }}  
          envkey_DB_PORT: ${{ secrets.ENVKEY_DB_PORT }}  
          envkey_DB_USERNAME: ${{ secrets.ENVKEY_DB_USERNAME }}  
          envkey_REDIS_CLIENT: ${{ secrets.ENVKEY_REDIS_CLIENT }}  
          envkey_REDIS_HOST: ${{ secrets.ENVKEY_REDIS_HOST }}  
          envkey_REDIS_PASSWORD: ${{ secrets.ENVKEY_REDIS_PASSWORD }}  
          envkey_REDIS_PORT: ${{ secrets.ENVKEY_REDIS_PORT }}
          envkey_APP_ENV: ${{ vars.ENVKEY_APP_ENV }}  
          envkey_APP_NAME: ${{ vars.ENVKEY_APP_NAME }}  
          envkey_CACHE_STORE: ${{ vars.ENVKEY_CACHE_STORE }}   
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate app key
        run: php artisan key:generate --force

      - name: Clear and cache config
        run: |
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Create deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "tests/*" "storage/logs/*" "storage/framework/cache/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: keyvalue-app
          environment_name: keyvalue-app-env
          version_label: ${{ github.sha }}
          region: ap-southeast-1
          deployment_package: deploy.zip
          wait_for_deployment: true 